#!/bin/bash
echo '***** Tests *****'
echo ' '
python3 -m unittest interpreter_test.py tokeniser_test.py -v
coverage run interpreter_test.py tokeniser_test.py
coverage html
echo ' '
echo '***** Coverage *****'
echo ' '
coverage report -m
echo ' '
echo '***** Done *****'
